package com.kellyfj.classifier;

import java.io.IOException;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.kellyfj.classifier.algo.KNNClassifier;
import com.kellyfj.classifier.data.DataHolder;
import com.kellyfj.classifier.data.DataLoader;
import com.kellyfj.classifier.data.DataRow;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'frankkelly' at '8/23/14 1:25 PM' with Gradle 2.0
 *
 * @author frankkelly, @date 8/23/14 1:25 PM
 */
public class ExperimentDriver {
	private static final Logger log = LogManager.getLogger();
	
	public static void main(String[] args) {
		//Load data
		DataHolder data = null;
		try {
			data = DataLoader.load("iris.data");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		int rows = data.size();
		log.info("Loaded "+rows +" rows");
		//Parse data
		
		//Train
		KNNClassifier knn = new KNNClassifier(5);
		knn.train(data);
		
		//Test
		for(DataRow d : data) {
			String classLabel = knn.test(d);
			break;
		}
	}
}
